### ISSUE TITLE
_pygit2.GitError: reference 'refs/heads/master' not found

### ISSUE THREAD

**Issue by jordr** [srg-imperial/diffanalyze#6]
Getting this error on `master`:

```
~/bench $ git clone https://github.com/raysan5/raylib
 ~/bench/raylib  master $ ~/code/diffanalyze/diffanalyze.py -s .


Traceback (most recent call last):
  File "/home/jruiz/code/diffanalyze/diffanalyze.py", line 730, in <module>
    main(sys.argv[1:])
  File "/home/jruiz/code/diffanalyze/diffanalyze.py", line 710, in main
    repo_manager.get_updated_fn_per_commit(args['skip'])
  File "/home/jruiz/code/diffanalyze/diffanalyze.py", line 512, in get_updated_fn_per_commit
    commits = list(patch_repo.walk(patch_repo.head.target, pygit2.GIT_SORT_TOPOLOGICAL))
_pygit2.GitError: reference 'refs/heads/master' not found
```

Haven't looked into it much yet

**Comment by MartinNowack** [comment]
Can you check if this is still an issue?

**Comment by jordr** [comment]
No-ish! I get
```
~/bench $ git clone https://github.com/raysan5/raylib
 ~/bench/raylib  master $ ~/code/diffanalyze/diffanalyze.py -s .
_pygit2.GitError: 6da3c1e7c3808e06efd110903222c2be8971e589: cannot reset hard. This operation is not allowed against bare repositories.
```

possibly fixed the original issue with all the update shenanigans I went through for https://github.com/srg-imperial/diffanalyze/issues/9

**Comment by MartinNowack** [comment]
Can you clone this repository again? It looks like it's cloned as a `--bare` repository.

**Comment by jordr** [comment]
@MartinNowack I did a reclone like you can see in the shell log. I also removed the `repo`, `repo_prev` folders.

**Comment by MartinNowack** [comment]
@jordr Sorry, wrongly phrased question. Is this an issue with the `diffanalyze2.py`?
I didn't fix anything within the original script.

**Comment by jordr** [comment]
@MartinNowack Absolutely not, `diffanalyze2.py` works like a breeze ;-)
The only downside to it is that it's less fun to trial-and-error because of the lack of cache

**Comment by MartinNowack** [comment]
oh, believe me - i do love wasting my time as well :D

**Comment by MartinNowack** [comment]
but you know you can also just use a local repository - just to bring back the fun into life ;)

**Comment by jordr** [comment]
@MartinNowack I always use a local repository, the thing is that it now seems to clone the repository into the meanders of `/tmp/`, never to find it again. This warmup time is repeated at each execution, as far as I can tell

**Comment by MartinNowack** [comment]
@jordr it should not clone it. But it "exports" single files of interest to analyse them with `ctags`. Do you have some numbers?

**Comment by MartinNowack** [comment]
Can you post the output of an example?

**Comment by jordr** [comment]
> @jordr it should not clone it. But it "exports" single files of interest to analyse them with `ctags`.

My bad then, I thought it behaved like the old `diffanalyze.py`
Probably my memories of `diffanalyze.py`'s behaviour on large repository was positively altered then. My `diffanalyze.py` is broken because of... https://github.com/srg-imperial/diffanalyze/issues/6 so I can't give you any numbers

**Comment by jordr** [comment]
By the way, it should be noted that `sudo apt install ctags` on Ubuntu 18.04 installs `exuberant-ctags`, which do not have the option `--quiet`, so the script does not work. I used `snap install ctags` instead to get `universal-ctags`.

**Comment by MartinNowack** [comment]
@jordr Don't use that script it should not be used in the first place.
