### ISSUE TITLE
diffanalyze2: cannot open input file "/tmp/tmp95ff2pyqKeeper.cpp" : No such file or directory

### ISSUE THREAD

**Issue by jordr** [srg-imperial/diffanalyze#7]
Most repository/commits lead to this error:

```
~/code/autochopper-pspa/utils/diffanalyze/diffanalyze2.py ~/code/autochopper-pspa --new-revision HEAD --old-revision HEAD~10
WARNING:Submodule update detected diffanalyze but currently not supported.
Traceback (most recent call last):
  File "/home/jruiz/code/autochopper-pspa/utils/diffanalyze/diffanalyze2.py", line 274, in <module>
    main(sys.argv[1:])
  File "/home/jruiz/code/autochopper-pspa/utils/diffanalyze/diffanalyze2.py", line 269, in main
    results = generate_repository_changes(args.repo, args.new_revision, args.old_revision)
  File "/home/jruiz/code/autochopper-pspa/utils/diffanalyze/diffanalyze2.py", line 145, in generate_repository_changes
    file_structure = fa.analyse_blob(file_blob.data, file_blob.name)
  File "/home/jruiz/code/autochopper-pspa/utils/diffanalyze/diffanalyze2.py", line 73, in analyse_blob
    return self.analyse_file(tf.name)
  File "/home/jruiz/code/autochopper-pspa/utils/diffanalyze/diffanalyze2.py", line 49, in analyse_file
    raise RuntimeError(err.decode('utf-8'))
RuntimeError: ctags: Warning: cannot open input file "/tmp/tmp95ff2pyqKeeper.cpp" : No such file or directory
```

**Comment by MartinNowack** [comment]
@jordr The problem is not the script but the way you installed snap:

https://snapcraft.io/universal-ctags

If installed via snap, ctags is not allowed to access `/tmp` therefore this access fails.

**Comment by jordr** [comment]
Ahh, I see. My bad, I'll look for an `apt` package to avoid future problems

**Comment by MartinNowack** [comment]
@jordr no, no - that was not obvious at all . I could just accidentally reproduce it and later fix it while testing on an Ubuntu.

**Comment by 251** [comment]
Just deinstall snap - it's completely useless. ;)
