### ISSUE TITLE
_pygit2.Tree operation is unsupported, probably a missing package requirement?

### ISSUE THREAD

**Issue by jordr** [srg-imperial/diffanalyze#9]
diffanalyze2 is working fine on my personal machine.
When I run it on the office machine, I get

```
jruiz@tamwoorth:~/code/exp-rebased/auto-libtasn1$ ~/code/autochopper-pspa/scripts/diffanalyze2.py libtasn1-git/
Traceback (most recent call last):
  File "/home/jruiz/code/autochopper-pspa/scripts/diffanalyze2.py", line 279, in <module>
    main(sys.argv[1:])
  File "/home/jruiz/code/autochopper-pspa/scripts/diffanalyze2.py", line 274, in main
    results = generate_repository_changes(args.repo, args.new_revision, args.old_revision)
  File "/home/jruiz/code/autochopper-pspa/scripts/diffanalyze2.py", line 123, in generate_repository_changes
    commit_change = generate_commit_change(fa, repository, commit)
  File "/home/jruiz/code/autochopper-pspa/scripts/diffanalyze2.py", line 143, in generate_commit_change
    file_blob = retrieve_file_from_commit(commit, file_name)
  File "/home/jruiz/code/autochopper-pspa/scripts/diffanalyze2.py", line 208, in retrieve_file_from_commit
    tree = tree / e  # type: pygit2.Tree
TypeError: unsupported operand type(s) for /: '_pygit2.Tree' and 'str'
```

is there a missing dependency somewhere?

**Comment by jordr** [comment]
So apparently the pygit2 from `pip 18.1` is broken and `pip 19.0+` fixes this.

**Comment by ccadar** [comment]
Can you document this somewhere?  Or even better, enforce >= 19?

**Comment by MartinNowack** [comment]
Right, they have an explicit message there on pygit2: https://www.pygit2.org/install.html#quick-install

**Comment by jordr** [comment]
@MartinNowack we could still add a mention of this in the README?

**Comment by MartinNowack** [comment]
@jordr I do agree. I was kind of hoping that pygit2 warns about this but unfortunately it doesn't.
